# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: phyothant
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL, "test"}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
